filebeat.inputs:
- type: filestream
  id: my-filestream-id
  enabled: false
  paths:
    - /var/log/*.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true

setup.template.settings:
  index.number_of_shards: 1

output.logstash:
  hosts: ["syslog.estrada.co.id:5044"]
  ssl.certificate_authorities: ["/etc/filebeat/certs/ca/isrgrootx1.pem"]

processors:
  - add_host_metadata:
      geo:
        region_name: "cyb"
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
